services:
  - type: web
    name: yara-frontend
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    buildCommand: ""
    startCommand: ""

